// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxlvfhvicwjmzhonlllo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bHZmaHZpY3dqbXpob25sbGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NDQzMTUsImV4cCI6MjA5MTEyMDMxNX0.6tzK_Ce3cwVa4Bj3zHUfX8YUt-EbVA0-Kc-382TSDeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});